Pyfile_enviroment

diff --git a/0x00-python-hello_world/0-run b/0x00-python-hello_world/0-run
--- a/0x00-python-hello_world/0-run
+++ b/0x00-python-hello_world/0-run
@@ -1,2 +1,14 @@
 #!/bin/bash
-python3 ./*.py
+
+if [ -z "PYFILE" ]; then
+	echo "Error PYFILE enviroment variable is not sent"
+	exit 1
+fi
+
+
+if [ -f "PYFILE" ]; then
+	echo "PYFILE exists"
+	exit 1
+fi
+
+python3 "$PYFILE"
